### ISSUE TITLE
Light level overlay ghosting 

### ISSUE THREAD

**Issue by Syntaxvgm** [sakura-ryoko/minihud#17]
I see there's a fix note in the latest release, but I'm on that version and still have the issue when I relight unit areas, red borders don't go away. I only made this because of the fix note in the release, sorry if this something you already know about. 

minihud-fabric-1.21-0.31.999-sakura.9

https://github.com/user-attachments/assets/8e32cd2d-ec15-4802-94c8-045e06761bca

**Comment by Ka1nnn** [comment]
i can confirm this as well ive seen it happen quite a few times

**Comment by sakura-ryoko** [comment]
Seems related to an older fix from sakura 2 or 3 that may have missed a specific case of the Rendering Base not cleaning up the vertexBuffer.
What was happening is, under 1.21 for whatever reason, after it draws the vertexBuffer, and it is no longer needed, the vertexBuffer needs to be closed / cleaned up, or else the image 'ghosts' on the screen like this.  It used to be worse.

**Comment by sakura-ryoko** [comment]
I think this is a case of Closing / Re-opening the vertexBuffer in between state changes.

**Comment by sakura-ryoko** [comment]
See if you can reproduce it with sakura.10
I didn't really change a lot, but figured I would try this.

https://github.com/sakura-ryoko/minihud/releases/tag/1.21-sakura.10
