### ISSUE TITLE
There's no background in the shulkerBoxPreview option

### ISSUE THREAD

**Issue by ProgramClass2** [sakura-ryoko/minihud#18]
Background in shulkerBoxPreview is completely invisible.
![2024-07-18_14 03 34](https://github.com/user-attachments/assets/34f683e7-1c23-41cc-bf85-13943ceea3fd)

**Comment by sakura-ryoko** [comment]
There is obviously some other mod changing how your MiniHUD rendering is working.

**Comment by ProgramClass2** [comment]
Yeah, it was EffectTimerPlus :/
