### ISSUE TITLE
virus?

### ISSUE THREAD

**Issue by itzsweats** [sakura-ryoko/minihud#21]
not saying this is a virus but when i go to download the file it fails and says virus detected.. help

**Comment by barlos08** [comment]
im getting the same thing.

**Comment by dewboy3d** [comment]
I believe it is a false positive. I've submitted a review to the Microsoft Defender ATP team.

**Comment by sakura-ryoko** [comment]
false positive.

**Comment by itzsweats** [comment]
so how do i download then bc my pc just wont allow it to download

**Comment by sakura-ryoko** [comment]
mark it as safe, somehow.
