### ISSUE TITLE
Weather info missing thundering

### ISSUE THREAD

**Issue by Aefinn** [sakura-ryoko/minihud#24]
Thank you for adding the weather info <3

Noticed that it still mislabels thundering as just raining

**Comment by sakura-ryoko** [comment]
I tested this and it labels thundering correctly.  The next release will show the Human-readable Time remaining instead of ticks remaining.

**Comment by sakura-ryoko** [comment]
See sakura.12, as I was not able to reproduce when it doesn't show 'Thundering' on the weather line.
