### ISSUE TITLE
1.21: Bee counter not working until you break the bee nest

### ISSUE THREAD

**Issue by Hellster90** [sakura-ryoko/minihud#26]
When you hover over a bee nest in a tree (before you silk touch it), it doesn't show how many bees are in it until after you break it, it always shows zero.
Once you break it and place it again it correctly shows the number of bees inside.

**Comment by sakura-ryoko** [comment]
This depends if you are on a server, and if that server has Servux installed.

**Comment by Hellster90** [comment]
> This depends if you are on a server, and if that server has Servux installed.

You mean if it's installed it doesn't work ? or the opposite ?

**Comment by sakura-ryoko** [comment]
Generally, you can't access the Block Entity Data for Beehives if you are playing on a server, until you silk touch it, and put it in your Inventory.  Then, after placing it back, you can see the data on the info Line for a limited amount of time.

With 1.21, and if modern versions of Servux (0.3.0+) are installed on the server, it can request this data, and Servux will send it to you.

**Comment by Hellster90** [comment]
> Generally, you can't access the Block Entity Data for Beehives if you are playing on a server, until you silk touch it, and put it in your Inventory. Then, after placing it back, you can see the data on the info Line for a limited amount of time.
> 
> With 1.21, and if modern versions of Servux (0.3.0+) are installed on the server, it can request this data, and Servux will send it to you.

Ok, I'll have a word with my friend who runs the server, thanks for the info :)
