### ISSUE TITLE
windows recognizes it as a virus

### ISSUE THREAD

**Issue by Holiseo** [sakura-ryoko/minihud#27]
![Untitled](https://github.com/user-attachments/assets/88990a29-8ebe-4e7e-9619-de8076f76991)

**Comment by relast** [comment]
Same here (perhaps a virus definition update just happened): 

![image](https://github.com/user-attachments/assets/6b3f1463-12cc-4006-9c24-d72daf2d49f4)

**Comment by sakura-ryoko** [comment]
False positive.
