### ISSUE TITLE
BeeTooltips has wrong Tooltip in Menu

### ISSUE THREAD

**Issue by morgantic** [sakura-ryoko/minihud#30]
![image](https://github.com/user-attachments/assets/f3776c93-8c04-4d3a-ad56-f893196cbd3e)

**Comment by sakura-ryoko** [comment]
This is obviously a bug with the JSON file.

**Comment by sakura-ryoko** [comment]
Fixed in next release sakura.13

**Comment by sakura-ryoko** [comment]
See https://github.com/sakura-ryoko/minihud/releases/tag/1.21-sakura.13
