### ISSUE TITLE
Structure overlays not working in multiplayer

### ISSUE THREAD

**Issue by Packsolite** [sakura-ryoko/minihud#31]
The structure overlays are just not working in multiplayer. I've set a seed using minihud-seed and also tried oping myself and running /seed. It says that the seed is set, but no overlays are rendering.
Tested using 1.21-sakura.13

**Comment by sakura-ryoko** [comment]
The structures on servers requires SERVUX to be installed on the server.

**Comment by wendavid552** [comment]
Could it set to a client side only mode? Just calculate the structures client side (with seeds), without sending them from servux? There are some server with e.g. Spigot, Paper, Forge, etc.

**Comment by wendavid552** [comment]
> The structures on servers requires SERVUX to be installed on the server.

Just setting the seeds is ok. It is possibly a render issue or compat issue with other rendering mods. Could you provide your mod list? @Packsolite

**Comment by sakura-ryoko** [comment]
> > The structures on servers requires SERVUX to be installed on the server.
> 
> Just setting the seeds is ok. It is possibly a render issue or compat issue with other rendering mods. Could you provide your mod list? @Packsolite

Incorrect.

The Seed has nothing to do with the Structure rendering.  It requires Servux on the server in order to function if you are not in Single Player.

The minihud-seed is only used for Slime Chunks.

**Comment by Packsolite** [comment]
> > The structures on servers requires SERVUX to be installed on the server.
> 
> Just setting the seeds is ok. It is possibly a render issue or compat issue with other rendering mods. Could you provide your mod list? @Packsolite

Slime chunks render perfectly fine. It's just the structures that don't render.
Here's my mod list:
![image](https://github.com/user-attachments/assets/41955945-f6cc-47da-aa58-52e29b8a867f)

**Comment by sakura-ryoko** [comment]
Like I said, the Server requires Servux to be installed or else the Structures will not work.
