### ISSUE TITLE
Crash when using inventory peak in minihud in singleplayer

### ISSUE THREAD

**Issue by ARedstoneMan** [sakura-ryoko/minihud#32]
Crash report: https://mclo.gs/1xhMiYM
Minihud version: sakura.14

not sure what is going on here, might be a mod conflict or something.

**Comment by ARedstoneMan** [comment]
Also, there is intense lag when holding down the inventory peek key, even when not looking at an inventory. this did not happen with tweakeroo's inventory peek, which ive been using for a while.

**Comment by sakura-ryoko** [comment]
For next release version

**Comment by sakura-ryoko** [comment]
If you continue having problems with sakura.15, please repost.

**Comment by ARedstoneMan** [comment]
If I hold down the key for inventory preview in sp, this ui shows up regardless of if you're looking at a container at all, doesn't correctly show inventory contents at all either as shown here (shows chest inv ui despite looking at a hopper)
![image](https://github.com/user-attachments/assets/1623c88b-48c7-4979-820b-12772f744a99)

**Comment by sakura-ryoko** [comment]
Okay, please try sakura.16 -- I have disabled the code that is causing the above screen shot until zly can address it.

https://github.com/sakura-ryoko/minihud/releases/tag/1.21-sakura.16

(I also made the Horse / Wolf Armor work again)

**Comment by sakura-ryoko** [comment]
This issue has been fixed.
