### ISSUE TITLE
Kicked from multiplayer when Inventory Previewing a chest full of boxes of full beehives

### ISSUE THREAD

**Issue by Falsus2** [sakura-ryoko/minihud#38]
This is so unbelievably niche, but I thought I might as well report it if its fixable. Title is exactly as claimed. Here is a screenshot of the kick message: 
![image](https://github.com/user-attachments/assets/35e4091e-25aa-42f6-9546-d1e497619401)
It seems that 12 shulker boxes of full bee hives is the limit before you get kicked. 

This is so game breaking!!!! (This is the dumbest thing I've ever seen, would not blame you if you ignore this)

**Comment by Falsus2** [comment]
Also heres a disconnect log: 
[disconnect-2024-06-17_17.43.00-client.txt](https://github.com/user-attachments/files/16475581/disconnect-2024-06-17_17.43.00-client.txt)

**Comment by sakura-ryoko** [comment]
Try updating your mods and sending a recent log file.
This log file is from June.
`Time: 2024-06-17 17:43:00`

**Comment by Falsus2** [comment]
> Try updating your mods and sending a recent log file. This log file is from June
. `Time: 2024-06-17 17:43:00`

Sorry I sent the wrong one by accident lol. Here's the the one I meant to send
[disconnect-2024-08-02_14.41.59-client.txt](https://github.com/user-attachments/files/16478191/disconnect-2024-08-02_14.41.59-client.txt)

**Comment by sakura-ryoko** [comment]
This 'should' fix it.  https://github.com/sakura-ryoko/minihud/releases/tag/1.21-sakura.20

**Comment by sakura-ryoko** [comment]
Also, I took a second look at your crash log and noticed it's coming from Tweakermore.
```
at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.ChannelInboundDelayer.lambda$channelRead$1(ChannelInboundDelayer.java:35)
	at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.DelayedRunner.delayedRun(DelayedRunner.java:49)
	at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.ChannelInboundDelayer.channelRead(ChannelInboundDelayer.java:33)
	```

**Comment by sakura-ryoko** [comment]
`tweakermore: TweakerMore 3.20.1` --> report this to Fallen Breath here:

https://github.com/Fallen-Breath/tweakermore/issues

Please link this thread, and tell Fallen I said hi.  👍

**Comment by sakura-ryoko** [comment]
I still made the adjustments under MiniHUD to stop the MiniHUD entity_sync protocol from having a similar problem.

Also note that, MiniHUD along with Servux 0.3.x can also provide Entity Sync; if enabled; but if you want to use the Tweakermore Entity Sync, be sure to disable the MiniHUD code via these settings:

`entityDataSync` and `entityDataSyncBackup`

**Comment by Fallen-Breath** [comment]
> Also, I took a second look at your crash log and noticed it's coming from Tweakermore.
> 
> ```
> at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.ChannelInboundDelayer.lambda$channelRead$1(ChannelInboundDelayer.java:35)
> 	at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.DelayedRunner.delayedRun(DelayedRunner.java:49)
> 	at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.ChannelInboundDelayer.channelRead(ChannelInboundDelayer.java:33)
> 	```
> ```

It's not related to tweakermore as the issue is caused by packet deserialization. Tweakermore's `connectionSimulatedDelay` only works as a wrapper method here

**Comment by sakura-ryoko** [comment]
> > Also, I took a second look at your crash log and noticed it's coming from Tweakermore.
> > ```
> > at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.ChannelInboundDelayer.lambda$channelRead$1(ChannelInboundDelayer.java:35)
> > 	at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.DelayedRunner.delayedRun(DelayedRunner.java:49)
> > 	at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.ChannelInboundDelayer.channelRead(ChannelInboundDelayer.java:33)
> > ```
> 
> It's not related to tweakermore as the issue is caused by packet deserialization. Tweakermore's `connectionSimulatedDelay` only works as a wrapper method here

Thanks for your input.  Perhaps the above 'fix' might have done the trick regardless, hopefully.

**Comment by sakura-ryoko** [comment]
Let me know the results @Falsus2 .

**Comment by Falsus2** [comment]
> Let me know the results @Falsus2 .

Yep, seems to be fixed. Thanks 👍
