### ISSUE TITLE
Is a little visual error with the function light level block.

### ISSUE THREAD

**Issue by wilebaldo** [sakura-ryoko/minihud#40]
when I activated the light level block and is marked to show only the spawnable blocks if i move closed to those block this despairing, but i notice is making the player as light source.

![Screenshot 2024-08-05 at 23 03 00](https://github.com/user-attachments/assets/963ff129-a1a7-4040-950f-c599cd40a8af)
![Screenshot 2024-08-05 at 23 04 46](https://github.com/user-attachments/assets/d919492e-62ae-4cc9-a238-500f247f32ae)
![Screenshot 2024-08-05 at 23 04 52](https://github.com/user-attachments/assets/92fd3882-e20a-4356-9877-f859330149d7)
![Screenshot 2024-08-05 at 23 05 15](https://github.com/user-attachments/assets/a3cada76-5087-494d-bf4e-3a5bc83ae105)
![Screenshot 2024-08-05 at 23 05 21](https://github.com/user-attachments/assets/98ed1f37-7212-4bfc-aea9-a97e26d661b9)
![Screenshot 2024-08-05 at 23 05 29](https://github.com/user-attachments/assets/b451d902-2932-42dd-b2e4-8cce71e63e07)

**Comment by sakura-ryoko** [comment]
There have been fixes to this in revisions.  Please upgrade to sakura.20+ .
Also, other mods cause the player to "Become a Light Source" .
