### ISSUE TITLE
Light level overlay ghost low light level squared [1.21 sakura.20]

### ISSUE THREAD

**Issue by danivenk** [sakura-ryoko/minihud#42]
Using the light level overlay in version [1.21-sakura.20](https://github.com/sakura-ryoko/minihud/releases/tag/1.21-sakura.20), sometimes when I put down a light source yellow squares appear that don't seem to go away even tho the block has a light level bigger than 0. The squares even don't seem to be aligned with the actual blocks.
![2024-08-07_22 17 54](https://github.com/user-attachments/assets/1d4c79c2-1cd3-4e3d-b137-7078e0de6a26)

**Comment by sakura-ryoko** [comment]
Perhaps this is due to another mod changing the block / lightning conditions ?

**Comment by danivenk** [comment]
This could be the case since I can't seem to reproduce it when only using Minihud as my mod. However, I have no clue which other mod might be causing it, nor why the overlay would show the grid of yellow squares not aligned with blocks.
The only thing I can think of why it would do this is that it shows the light levels for blocks that aren't currently the surface you are looking at or something. 🤔

Edit:
![2024-08-10_21 59 56](https://github.com/user-attachments/assets/5f9e0e13-1db8-4e60-959b-74069b5a447d)
K apparently when coming from the Nether it gets much worse. Almost looks like the terrain which was here before I mined it down. As for how it usually happens is when I place a new light source after breaking one after mining a part.  It doesn't always happen but it does happen quite often for me.

Edit2:
I did some more trying and yes it still happens when I'm only using the following mods (Fabric API 0.100.3, MaLib 0.20.2, Minihud 0.31.999). For when it happens please look at the text above.

**Comment by sakura-ryoko** [comment]
There are already known visual glitches under certain conditions with the light level overlay.  It was mainly related to when Mojang changed how the VBO/Rendering buffers are handled.  The problem is mainly fixed; but there is still an unknown condition that the "invalid overlays" still shows because the VBO buffer hasn't been closed yet with the fixed code.  Usually it goes away on it's own or if you keep moving.

**Comment by sakura-ryoko** [comment]
Try sakura.23.  I took the VBO recycling to the extreme a bit.  Less performance for the overlay?  Maybe ...

https://github.com/sakura-ryoko/minihud/releases/tag/1.21-sakura.23

**Comment by danivenk** [comment]
This seems to indeed have fixed it (or at least made it less prevalent), thank you for your time/work.
