### ISSUE TITLE
Display text can be translated by resourcepack

### ISSUE THREAD

**Issue by ChinoKou** [sakura-ryoko/minihud#44]
I'm using version Sakura.20 in 1.21
Minihud display text can't be translated into other language by resourcepack
Have any intentions to realize this like MasaGadget？
[MasaGadget-minihudI18n](https://github.com/plusls/MasaGadget/blob/main/README_EN.md#Minihud)

**Comment by sakura-ryoko** [comment]
The lang files for MiniHUD already includes translations.  If there is a language that is not supported, offer a PR.

**Comment by sakura-ryoko** [comment]
See https://github.com/sakura-ryoko/minihud/releases/tag/1.21-sakura.21
