### ISSUE TITLE
Severe memory leak leading to crash when open the display of villager information(overlayVillagerInfo)

### ISSUE THREAD

**Issue by Hx-zh** [sakura-ryoko/minihud#48]
![turn on](https://github.com/user-attachments/assets/29ad05df-44ba-41f1-8d91-ff0a3ca4f655)
mod version：minihud-fabric-1.21-0.31.999-sakura.19
Fabric&minecraft version：1.21.1-Fabric 0.15.11
When I turn on this feature, with some villagers selling enchanting books , I can observe in the task manager that the memory occupied by the Java process is increasing rapidly.（more than 1MB/s）
After a period of time, this will cause the game to crash

and here are my mod list
```txt
architectury-13.0.6-fabric.jar
fabric-api-0.102.1+1.21.1.jar
fabric-language-kotlin-1.12.0+kotlin.2.0.10.jar
ftb-library-fabric-2100.1.4.jar
ftb-ultimine-fabric-2100.1.0.jar
itemscroller-fabric-1.21-0.24.0.jar
libIPN-fabric-1.21-6.0.2.jar
litematica-fabric-1.21-0.19.0.jar
malilib-fabric-1.21-0.20.2.jar
minihud-fabric-1.21-0.31.999-sakura.19.jar
placeholder-api-2.4.1+1.21.jar
syncmatica-fabric-1.21-0.3.12-sakura.3.jar
tweakeroo-fabric-1.21-0.20.999-sakura.22.jar
YetAnotherConfigLib-3.5.0+1.21-fabric.jar
Zoomify-2.14.0+1.21.jar
gugle-carpet-addition-mc1.21-2.9.0+build.52.jar
jei-1.21-fabric-19.8.2.99.jar
XaerosWorldMap_1.38.8_Fabric_1.21.jar
Xaeros_Minimap_24.2.1_Fabric_1.21.jar
InventoryProfilesNext-fabric-1.21-2.0.4.jar
CustomSkinLoader_Fabric-14.20.jar
fabric-carpet-1.21-1.4.147+v240613.jar
litematica-printer-1.21-3.5.0-sakura.4.jar
modmenu-11.0.1.jar
toms_storage_fabric-1.21-2.0.9.jar
shulkerboxtooltip-fabric-5.0.4+1.21.jar
inventoryhud.fabric.1.21-3.4.24.jar
Jade-1.21-Fabric-15.1.5.jar
appleskin-fabric-mc1.21-3.0.5.jar
jecharacters-fabric-4.5.14.jar
sodium-extra-0.5.7+mc1.21.jar
sodium-fabric-0.5.11+mc1.21.jar
pinyined-masa-0.6.jar
```

**Comment by sakura-ryoko** [comment]
Can you post the actual crash log ?
Also, are you on a server, and I am assuming that it doesn't have Servux installed, and you are not OP ?

**Comment by Hx-zh** [comment]
1.Unfortunately，when the memory leaks completely, it will cause my launcher to crash and unable to collect crash logs. I will try to collect more information later.
2.Both local and server have this issue . By the way ,I am OP and there is no difference in the phenomenon before and after installing Servux.

**Comment by sakura-ryoko** [comment]
Can you update your mods to the latest versions and try to reproduce ?

**Comment by Hx-zh** [comment]
update to minihud-fabric-1.21-0.31.999-sakura.23.jar and use a new package ，
Here is my file list
```
fabric-api-0.102.1+1.21.1.jar
malilib-fabric-1.21.1-0.21.0.jar
minihud-fabric-1.21-0.31.999-sakura.23.jar
```
After hanging up for a period of time, reproduce the memory leak but no crash. Memory usage returns to normal after reaching a very high level. The memory usage of Java processes once reached 9GB. The overall memory usage rate is 91%.
Perhaps other factors are needed to cause the game to crash. For example, there may be changes in the memory occupied by player activities or other backend applications. 

Although there was no game crash, I believe such a severe memory leak is very dangerous, as it initially caused my backend chat software to crash
![image](https://github.com/user-attachments/assets/d6e846f5-1b01-401c-bb48-75c5414ab407)

**Comment by sakura-ryoko** [comment]
Is this happening with ONLY those 3 mods installed, or do you have other mods still installed?  If so, try removing them and seeing if you can reproduce it.

**Comment by Hx-zh** [comment]
ONLY

**Comment by sakura-ryoko** [comment]
Can you check to see if the same happens with the updated versions ?  thanks.

**Comment by ksdh2333** [comment]
Reproduced in versions 1.21-0.32.52, no matter how much memory is allocated, memory overflow will occur within a few hours
[2024-11-25-2.log](https://github.com/user-attachments/files/17896572/2024-11-25-2.log)

**Comment by sakura-ryoko** [comment]
What the log states has nothing to do with the Villagers:
```
java.lang.OutOfMemoryError: Cannot reserve 4194304 bytes of direct buffer memory (allocated: 2143601740, limit: 2147483648)
-->
at net.minecraft.class_2540.readBytes(class_2540.java:1267) ~[client-intermediary.jar:?]
	at fi.dy.masa.malilib.network.PacketSplitter$ReadingSession.receive(PacketSplitter.java:139) ~[malilib-fabric-1.21-0.21.2.jar:?]
	at fi.dy.masa.malilib.network.PacketSplitter.receive(PacketSplitter.java:75) ~[malilib-fabric-1.21-0.21.2.jar:?]
	at fi.dy.masa.malilib.network.PacketSplitter.receive(PacketSplitter.java:66) ~[malilib-fabric-1.21-0.21.2.jar:?]
	at fi.dy.masa.minihud.network.ServuxStructuresHandler.decodeStructuresPacket(ServuxStructuresHandler.java:81) ~[%5B迷你HUD%5D%20minihud-fabric-1.21-0.32.52.jar:?]
	at fi.dy.masa.minihud.network.ServuxStructuresHandler.receivePlayPayload(ServuxStructuresHandler.java:158) ~[%5B迷你HUD%5D%20minihud-fabric-1.21-0.32.52.jar:?]
	
-->
[10:04:47] [Netty Client IO #38/ERROR]: ServuxStructuresPacket#fromPacket: input buffer is not empty, skipping remaining bytes. are you using the correct version?
```

If anything, it looks like your server is sending you Structures Packets; and for some reason doesn't seem to be the correct packets; where the PacketSplitter isn't able to reassemble the packets and runs out of memory from it's buffers filling up.

Normally, this is a process that only takes a couple ms, and then it flushes the buffers.  What version of Servux are you using on the server side ???
That error was coded in to highlight when people are trying to use the wrong Versions of Servux / Minecraft; such as trying to mix old versions (1.20.4 and below) with the current; like with the `ViaVersion` type of crap.

**Comment by ksdh2333** [comment]
The version of Servux I used when my game made an error was 1.21-0.3.8-sakura. 2, and I didn't notice it was updated. I am currently testing it with the latest version.

I'm sorry that I mistakenly reported a bug again.
