### ISSUE TITLE
[BUG]容器预览会导致玩家本身物品堆叠数量丢失

### ISSUE THREAD

**Issue by 18895kmxk** [sakura-ryoko/minihud#49]

**Comment by Chormore-EDGE** [comment]
倒是带个截图啊老哥
![image](https://github.com/user-attachments/assets/62b9fc71-0a6e-4edd-a823-e1b5fa666217)

**Comment by sakura-ryoko** [comment]
And what is the issue ?
You seem to have another "Shulker box/Tooltip" display mod installed that is not MiniHUD.

**Comment by 18895kmxk** [comment]
“Other module issues have been resolved.”

**Comment by 18895kmxk** [comment]
Other module issues
