### ISSUE TITLE
On the 1.21 Fabric server, you cannot use the renderer to render any structure

### ISSUE THREAD

**Issue by Chormore-EDGE** [sakura-ryoko/minihud#50]
I'm sure I've loaded the Servux mod on the server,and I tried to update to the latest version of Minihud and Malilib,but it still doesn't work,

**Comment by sakura-ryoko** [comment]
I need more details than this; such as:
- Versions of all mods
- Is the structure rendering turned ON, are the Structure types turned ON
- If all of the above is done, then I need to see log files, such as enabling the MiniHUD Debug logging.

**Comment by sakura-ryoko** [comment]
Also, its not a BUG if its not confirmed to even BE a bug.

**Comment by Chormore-EDGE** [comment]
there are versions of all mods
![image](https://github.com/user-attachments/assets/ab4ceb89-aa7b-4f0a-843e-51d82285cfa4)
![image](https://github.com/user-attachments/assets/4ba74ab7-6d8d-4242-b6af-fbe77c81ce0a)
![image](https://github.com/user-attachments/assets/25bed3a8-af15-41b1-b6fc-f6ad7b340643)
and I'm sure that's all done

**Comment by Chormore-EDGE** [comment]
I don't seem to be able to find where the minihud's log file is, could you tell me where it is？

**Comment by sakura-ryoko** [comment]
Servux is a server-side-only mod, it has no business being installed with client-side mods.  I would need to see the server mod list with Servux.
The MiniHUD logging is enabled via Generic->debugLogging, and check your Game Log.

Also, Servux 0.2.0 should work for 1.21; but there also exists Servux 0.3.7 for 1.21, which has a lot more features.
