### ISSUE TITLE
[Bug]容器预览无法查看比较器的红石能量强度

### ISSUE THREAD

**Issue by AbroadSphere** [sakura-ryoko/minihud#51]
使用minihud的容器预览时无法查看比较器的红石能量强度

**Comment by AbroadSphere** [comment]
@sakura-ryoko

**Comment by sakura-ryoko** [comment]
Google translated:
```
Cannot see the redstone power intensity of the comparator when using the container preview of the minihud
```

MiniHUD wasn't designed to show power levels, but Tweakermore has this feature.  I am going to assume that you mean for 'Placed' Comparators, because the `container preview` is meant to display containers and not redstone power levels.

https://modrinth.com/mod/tweakermore
