### ISSUE TITLE
渲染村民第一本书字体会透过方块

### ISSUE THREAD

**Issue by StevenHuang0330** [sakura-ryoko/minihud#53]
![Uploading A53E3F47DFE9BB7A6B960E7684DFCCD1.png…]()

**Comment by sakura-ryoko** [comment]
The link above is to this Issue page.

**Comment by sakura-ryoko** [comment]
'渲染村民第一本书字体会透过方块' --> Google translated:
```
Rendering the first book of villagers will show text through blocks
```

**Comment by sakura-ryoko** [comment]
I believe the Text Display is intended to be seen through blocks ?

**Comment by StevenHuang0330** [comment]
I'm sorry I didn't ask questions in English. When you open the first book, the text will pass through the box, which will cause serious visual fatigue.This feature is supposed to be ported from masa gadget and didn't have this problem before 1.21

**Comment by sakura-ryoko** [comment]
It's not a direct port of their code, but I do agree that this feature needs some work.
