### ISSUE TITLE
1.21-0.32.50-sakura.1 not compatible with Tweakermore

### ISSUE THREAD

**Issue by morgantic** [sakura-ryoko/minihud#57]
I almost went and got the release from modrinth, but found the comment "not compatible with Tweakermore" on here by chance. 

What exactly is not compatible? I heavily rely on Tweakermore so if it's just a temporary incompatibility I'd rather use an old minihud version for now... Thanks!

**Comment by sakura-ryoko** [comment]
Assuming that Fallen takes care of this by 1.21.2; it should be temporary.  I also advise people to hold off on updating it.
