### ISSUE TITLE
Set SpawnChunksReal value?

### ISSUE THREAD

**Issue by Greg-Malski** [sakura-ryoko/minihud#59]
Is there a way to set what value is used for Spawn Chunks Real? My server is still at a radius of 10, but whenever I render the Spawn Chunks, MiniHUD defaults to 2, and I can't find a way to change it.

**Comment by sakura-ryoko** [comment]
Usually Servux fixes this for you; but there is the chat-pseudo-command that you can use either: `minihud-spawnchunkradius <value>` or `/minihud-spawnchunkradius <value>`

MiniHUD also can read the value from the `/gamerule spawnChunkRadius` command if you have OP.
