### ISSUE TITLE
infoLookingAtEntity and infoEntityVariant don't work in multiplayer 1.21.3

### ISSUE THREAD

**Issue by m-sarabi** [sakura-ryoko/minihud#61]
The info `infoLookingAtEntity` and `infoEntityVariant` work in single-player but not multiplayer.

**Comment by sakura-ryoko** [comment]
They require having OP permissions or Servux installed.

**Comment by m-sarabi** [comment]
It was working on 1.21.1 and before, and the NBT info is still available and is sent to the client. I can get them in the current version using mods like clientcommands.

**Comment by sakura-ryoko** [comment]
I can't duplicate the problem.  Works with Servux obviously, and without (only carpet mod) using OP privileges as shown in the screen shots.  Without OP the NBT information is not available Client Side.

![2024-10-31_19 57 50](https://github.com/user-attachments/assets/29a7dcc8-5ab9-4d4f-b717-2c335736261a)
![2024-10-31_19 58 19](https://github.com/user-attachments/assets/f5a7b2b1-b41d-4bbe-a587-032ddd953075)
![2024-10-31_19 58 24](https://github.com/user-attachments/assets/441aacc1-9692-4cf7-bbe9-fccc0e948cca)
![2024-10-31_19 58 27](https://github.com/user-attachments/assets/5ea8fb89-60ad-4cbe-a777-3eeebf4e5df8)
![2024-10-31_19 58 52](https://github.com/user-attachments/assets/050a0b7e-bb49-4330-a663-cc011b76d0ac)
![2024-10-31_19 59 00](https://github.com/user-attachments/assets/24d42204-7d9e-4987-9b58-58c7a8ef76b6)

**Comment by m-sarabi** [comment]
Thanks for your attention, I appreciate it. I think I did not describe the issue clearly. In the screenshot below I'm on a 1.21.3 multiplayer server, I'm not OP and it does not have the `servux` mod:

![2024-11-01_08 45 56](https://github.com/user-attachments/assets/c63ce00a-47ce-40df-99da-2f37ada9bc58)

As we can see the minihud info for the entity is not working (I tried it with infoLinesUseNBT on and off).

But obviously some infos are sent to the client, for example if the color of the sheep was not available on the client, It couldn't know it is a white sheep or another color.

So I used the command `/cgetdata entity` from clientcommands mod, and as seen in the screenshot, the color and the health of the mob are present `Health: 8.0f, Color: 0b` (even though some NBT data are not present or wrong, like `age`).

In versions 1.21.1 and before, minihud would use that info to show them when using `infoLookingAtEntity`, but it broke in the 1.21.3 version.

Here is another example of a pillager that is damaged to 10 health (instead of 24), the hand item is broken, and is renamed to Seza:

![2024-11-01_09 02 18](https://github.com/user-attachments/assets/40697637-c6d4-4497-9506-697835c0bd01)

I hope it describes the issue.

**Comment by sakura-ryoko** [comment]
Yeah the Health line should work without OP, at minimum, and if the entity is owned by another player.  The sheep color I am not 100% on, but if it shows the Color Tag on the client side, it might.

Note that under the latest MiniHUD and Snapshot / 1.21.3 versions of MiniHUD I had to rewrite how the mod obtains data, and prioritize using the NBT tags if obtainable due to mod conflicts with other mods.

**Comment by sakura-ryoko** [comment]
I'll take another look at it.  Obviously because the code is such a major change I am sure there was a logic flow that was missing, regarding it's ability to obtain NBT tags when not OP, or without Servux; then it **should be defaulting** to the original behavior; but it apparently is not.

**Comment by sakura-ryoko** [comment]
I was able to fix the problem, but in so doing; I found another bug that I am working on with specific `inventoryPreview` situations using the Data Sync Backup mode.

**Comment by sakura-ryoko** [comment]
See https://github.com/sakura-ryoko/minihud/releases/tag/1.21.3-0.33.0-sakura.4

**Comment by sakura-ryoko** [comment]
Also, as an update, all of the `infoEntityVariant` works without having OP, nor Servux; as you have stated it should.

**Comment by m-sarabi** [comment]
I just tested it, and it works great. I know these recent updates broke many mods, so thank you so much for keeping them updated.
