### ISSUE TITLE
Shulker Preview not on top

### ISSUE THREAD

**Issue by manchesterjm** [sakura-ryoko/minihud#63]
When looking at a shulkerbox for the preview in the inventory screen, it is merged with the potion/beacon effects and is not on top  I am using 0.33.0-sakura.4 version

![image](https://github.com/user-attachments/assets/23c9e0fe-cb97-4e1f-931e-99b97b184ac1)

**Comment by sakura-ryoko** [comment]
Thanks for your report, so I was able to fix this generally for the Shulker Box Preview code, and actually expanded it's supported block types, such as for the Pick Block Crafter, with locked slots to display correctly using the Shulker Preview code.

**Comment by sakura-ryoko** [comment]
Upcoming release.

**Comment by manchesterjm** [comment]
awesome

**Comment by sakura-ryoko** [comment]
> awesome

It's MaLiLib that needs to be updated to fix this problem:
https://github.com/sakura-ryoko/malilib/releases/tag/1.21.3-0.22.0-sakura.4

But I need to build it against MiniHUD to verify it works, maybe even bump MiniHUD

**Comment by manchesterjm** [comment]
Gotcha.  I'm getting it now.

**Comment by manchesterjm** [comment]
Works perfect.  Thanks for the fix.

**Comment by manchesterjm** [comment]
Working perfectly
