### ISSUE TITLE
1.21.1: InventoryPreview does not show player ender chest contents or other players' inventories after latest update

### ISSUE THREAD

**Issue by kkellogg378** [sakura-ryoko/minihud#64]
With MiniHUD 0.32.50 / Servux 0.3.7, using InventoryPreview on a player would show their ender chest contents alongside their inventory. After updating to MiniHUD 0.32.51 / Servux 0.3.8, if I look at myself using freecam the ender chest just shows up as empty: 

![2024-11-12_22 54 41](https://github.com/user-attachments/assets/678170a9-7368-44c2-b1cb-650556b2dbaf)

and if I look at another player, their inventory is empty as well outside of the held item:

![2024-11-12_23 23 34](https://github.com/user-attachments/assets/ad19fa86-fd9b-42e3-adc5-fb9fdc4d8f71)

Side note, but I've found the only way to view my own ender chest data in the past is to use Tweakeroo's freecam and InventoryPreview myself (which is what I'm doing in that screenshot). It would be cool if InventoryPreview worked on placed ender chests and/or the ShulkerBoxPreview feature supported the ender chest

Final note: tweakermore and masa gadget are both disabled

**Comment by vocaloidkiss** [comment]
same

**Comment by vocaloidkiss** [comment]
@sakura-ryoko plz hurry up

**Comment by sakura-ryoko** [comment]
> @sakura-ryoko plz hurry up

Don't rush me.  I fix things on my own time.

**Comment by sakura-ryoko** [comment]
See the latest -sakura.X releases on here.  They require a MaLiLib update also.

**Comment by vocaloidkiss** [comment]
sorry qwq

**Comment by vocaloidkiss** [comment]
sever：malilib-fabric-1.21-0.21.2-sakura.1
servux-fabric-1.21-0.3.8

client：
malilib-fabric-1.21-0.21.2-sakura.1
servux-fabric-1.21-0.3.8
minihud-fabric-1.21-0.32.52-sakura.1

bug doesn‘t be fixed

**Comment by vocaloidkiss** [comment]
@sakura-ryoko

**Comment by sakura-ryoko** [comment]
I'll check it out further (Tomorrow); but I did have it working earlier.

**Comment by vocaloidkiss** [comment]
thanks

**Comment by kkellogg378** [comment]
Can confirm that the issue persists on the latest version with Servux 0.3.8, though I tested opening a singleplayer world to LAN and everything works okay there:

![2024-11-14_12 32 46](https://github.com/user-attachments/assets/37e8dc14-a945-478e-b631-9bd38c845709)

The shulkerBoxPreview feature for ender chests works fantastically on singleplayer as well!



Also @vocaloidkiss , let's not use unnecessary pings, since they can be annoying for the creator/maintainer. sakura is doing this free of charge, so we should be respectful of their time and grateful that they're going out of their way to fix the issue

**Comment by vocaloidkiss** [comment]
With those mods I have mentioned I am unable to reproduction this like you

**Comment by vocaloidkiss** [comment]
@kkellogg378

**Comment by kkellogg378** [comment]
@vocaloidkiss the screenshot I posted was in a single player world opened to LAN. I was just noting that the current issue seems to be related to the server/servux 0.3.8

**Comment by vocaloidkiss** [comment]
you are right

**Comment by sakura-ryoko** [comment]
I am in the middle of pushing a new fix tested with Servux (Servux and MaLiLib also needs updates)

**Comment by sakura-ryoko** [comment]
Okay, Please update [Servux to 0.3.9-sakura.1](https://github.com/sakura-ryoko/servux/releases/tag/1.21-0.3.9-sakura.1), and [MaLiLib 0.21.2-sakura.2](https://github.com/sakura-ryoko/malilib/releases/tag/1.21-0.21.2-sakura.2), and then [MiniHUD 1.21-0.32.52-sakura.2](https://github.com/sakura-ryoko/minihud/releases/tag/1.21-0.32.52-sakura.2) / Tweakeroo to fix this .

All assuming that you are using 1.21.  There are also 1.21.3 versions of the same.

**Comment by kkellogg378** [comment]
Issue is fully resolved now! Thank you!
