### ISSUE TITLE
NeoForge Port?

### ISSUE THREAD

**Issue by penturt** [sakura-ryoko/minihud#68]
Any plans to port/support NeoForge 1.21+?

**Comment by sakura-ryoko** [comment]
There is another person who has been cloning my code and trying to port them to work with NeoForge; and to answer your question more directly.

No plans.

**Comment by sakura-ryoko** [comment]
I believe you are looking for https://github.com/ThinkingStudios

**Comment by penturt** [comment]
Thank you 👍
