### ISSUE TITLE
villager info

### ISSUE THREAD

**Issue by itzsweats** [sakura-ryoko/minihud#72]
villager info lines not working, no matter what i do i cant see anything to do with villagers

**Comment by sakura-ryoko** [comment]
Villager Info Lines?  can you be more specific?  There are:
- Villager Info Overlay Renderer
- Villager Debug Renderers
- The actual Info Lines ?

**Comment by sakura-ryoko** [comment]
Also, if you are on a multiplayer server, in order to get ANY villager entity information beyond the basics (Health, etc), it requires a server side mod to send you the data to show.
