### ISSUE TITLE
Korean Crowdin lang files update request

### ISSUE THREAD

**Issue by MagPlum** [sakura-ryoko/minihud#74]
Hello, I would like to contribute a Korean translation for the MiniHUD mod. Here is my translation json file named 'ko_kr_2.json' just to distinguish. Please let me know if there is anything that needs to be corrected.
[ko_kr_2.json](https://github.com/user-attachments/files/17934612/ko_kr_2.json)

I have two more requests and two questions.

1. In Korean language setting, 'RESET' key is translated as '다시 놓기'. Please change it to '리셋'.
2. Also in the actionbar notification, 'ON' and 'OFF' are translated as '에' and '끄다'. Please change it back to 'ON' and 'OFF'.
3. Comments for 'lightLevelMarkerBlockLit' and 'lightLevelMarkerSkyLit' are same. Shouldn't (during day) in 'lightLevelMarkerBlockLit' be deleted?
4. In the comment to 'infoZombieConversion', it says (Husk) after skeleton. Shouldn't it be changed to (Stray)?

I always get a lot of help from the MiniHUD mod. Thank you very much.

![image](https://github.com/user-attachments/assets/44c9d69a-ff91-4f6e-a94c-133169c0ee4d)
![image](https://github.com/user-attachments/assets/56a2bd5c-8a86-42c1-a263-4b25fa5f93df)
![image](https://github.com/user-attachments/assets/12a9c193-82f3-4cf1-9a6e-e83f52411f7c)
![image](https://github.com/user-attachments/assets/7f51988c-db52-45b1-9327-da70222eac03)

**Comment by sakura-ryoko** [comment]
Yes, if the "RESET" and a few of the other translations of the Menus is wrong, there is also the lang file under malilib here, for example:
```
"malilib.gui.button.reset": "다시 놓기",
```
From --> https://github.com/sakura-ryoko/malilib/blob/665d8e09984bfc6647b2dfebfe82f2f3e3d1fb75/src/main/resources/assets/malilib/lang/ko_kr.json

**Comment by sakura-ryoko** [comment]
These lang files were introduced strictly from AI / Machine translations, so I am not surprised if they aren't very good, overall.

**Comment by sakura-ryoko** [comment]
With the `lightLevelMarkerBlockLit` I'm not too sure off hand, but I believe they are correct... I didn't write those two.

**Comment by MagPlum** [comment]
> Yes, if the "RESET" and a few of the other translations of the Menus is wrong, there is also the lang file under malilib here, for example:

I see, maybe I can translate that file someday. Thanks.


> With the `lightLevelMarkerBlockLit` I'm not too sure off hand, but I believe they are correct... I didn't write those two.

Spots marked by 'lightLevelMarkerBlockLit' are always spawn proofed by light source like torches or glowstones. So it doesn't have to specify as (during day). 
However spots marked by 'lightLevelMarkerSkyLit' are only spawn proofed by sunlight during day time. And I think that is why they wrote (during day) in the first place.
But ok. It is only my opinion so I don't insist.

Thank you for reply.

**Comment by sakura-ryoko** [comment]
Hello, Just an FYI, while I was doing my Crowdin cleanup, I have accidentally omitted your korean file for MiniHUD; and I've since re-added it to the Github repo.
Also, due to this, the Korean file under MaLiLib was removed also.  So, if you wish to have Korean under MaLiLib's prompts, also; you can help by doing MaLiLib's lang file also.

**Comment by sakura-ryoko** [comment]
The changes that I have done to MiniHUD today are these, and I have manually adjusted your ko_kr file.

I have primarily added this line from existing translations:
```json
"minihud.label.config_comment.server_side_data": "§6경고! 싱글 플레이어 또는 Servux의 서버 측 데이터가 필요합니다.",
```
And removed it from other lines in the current state of the repo.

This is a generalized message that now appears under Info Lines and Render Toggle Comments that requires Servux / Server Sided Data.

**Comment by sakura-ryoko** [comment]
Also, because I have fixed the "(Stray)" text, this line would need to be fixed.  I am not assuming the correct translation for it:

```json
"minihud.config.info_toggle.comment.infoZombieConversion": "Show the Time that a Zombie Villager,\nZombie (Drowned), or Skeleton (Stray) has\nuntil Conversion",
```

**Comment by MagPlum** [comment]
> Also, because I have fixed the "(Stray)" text, this line would need to be fixed. I am not assuming the correct translation for it:

The previous Korean translation had the word "stray" written in it. I tried making a pull request for it.
Please let me know if there is anything that needs to be corrected.
If there are no problems, I will use pull requests for future uploads and updates of Korean json files.

**Comment by sakura-ryoko** [comment]
Merged, thank you

**Comment by MagPlum** [comment]
> Merged, thank you

Now i can delete the fork used for the Pull request by "Delete this repository" button. Am I right?

**Comment by sakura-ryoko** [comment]
Yes
