### ISSUE TITLE
 Strange/incorrect sphere shapes

### ISSUE THREAD

**Issue by JamesSG2** [sakura-ryoko/minihud#78]
This issue still persists in Java 1.21.4! (Latest Minihud as of 12/13/24) Clearly these are not perfect spheres even when using the sphere shape in Minihud. They also don't agree with: https://www.plotz.co.uk/plotz-model.php?model=Sphere which I know has correct dimensions. Please fix this! Seems like the most basic feature of Minihud doesn't work correctly:

![image](https://github.com/user-attachments/assets/f8e52ad4-09d5-4811-9761-fea4ff25d207)
![image](https://github.com/user-attachments/assets/c94ec723-0a12-4e2a-a779-2a2fb7d7313b)

**Comment by sakura-ryoko** [comment]
This is a longtime outstanding "issue" that Masa has never fully addressed.

**Comment by JamesSG2** [comment]
Fixed it! See my fork pull request. Please review and incorporate these changes so the issue can be resolved. Thanks

**Comment by sakura-ryoko** [comment]
I'll test it out sometime later today.
Also, if you can research how to use Verified commits in the future; they are Verified / Certificate based Pushes.

**Comment by sakura-ryoko** [comment]
I've also notified Masa about this fix, because MiniHUD from around 1.18.X onwards has this problem.
